version: '3.7'

services:
  web:
    build:
      context: .
    volumes:
      - static_data:/vol/web
      - static_data:/vol/static

#  proxy:
#    build:
#      context: ./nginx
#    volumes:
#      - static_data:/vol/static
#    ports:
#      - "8080:8080"
#    depends_on:
#      - web

  volumes:
    static_data: